# Generated by Django 4.1.2 on 2022-10-31 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='application_linl',
            new_name='application_link',
        ),
    ]
